import Head from 'next/head'
import Link from 'next/link';

export async function getStaticProps({params}) {
    const res = await fetch(`${process.env.NEXT_PUBLIC_BACKEND_URL}/api/books/${params.bid}`)

    const data = await res.json()

    return {
        props: {
            book: data
        }
    }
}

export async function getStaticPaths() {
    const res = await fetch(`${process.env.NEXT_PUBLIC_BACKEND_URL}/api/books`)
    const data = await res.json()

    return {
        paths: data.map(book => ({
            params: {bid: String(book.id)}
        })),
        fallback: 'blocking'
    }
}
const BookDetail = ({ book }) => {
    return (
        <div>
            <Head>
            <title>BooksDetail</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            </Head>

            <h1>{book.title}</h1>
            <Link href="/libros">Book List</Link>
        </div>
    );
};

export default BookDetail;
